version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/apps/smart-contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/apps/report2earn/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/apps/ai-verification-module"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/apps/report2earn/ai-verify"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

